<?php
function webform_signup_menu(){
  $items = array();

  // Admin Settings.
  $items['admin/config/content/webform/signup'] = array(
    'title' => 'Webform singup settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_signup_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'description' => 'Global configuration of webform signup functionality.',
    'file' => 'webform_signup.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

	return $items;
}

function webform_signup_node_presave($node){
	if ($node->is_new) {
	  $node->webform['status'] = 0;
	}
}

function webform_signup_node_view($node, $view_mode) {
  if (!in_array($node->type, variable_get('webform_signup_node_types'))) {
    return;
  }

	$language = $node->language;
	$now = time();
	if (isset($node->webform_signup_date[$language][0]['value'])) {
		$date_start = $node->webform_signup_date[$language][0]['value'];
		if ($now < $date_start) {
			unset($node->content['webform']);
		}
	}
	if (isset($node->webform_signup_date[$language][0]['value2'])) {
		$date_end = $node->webform_signup_date[$language][0]['value2'];
		if ($now > $date_end) {
			unset($node->content['webform']);
		}
	}

}
